// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr4hgpdAJOADCpnXGv_U3atSSdwFsxdmc',
    appId: '1:500869155129:web:ce5720b0a079f932d8c0e8',
    messagingSenderId: '500869155129',
    projectId: 'fir-rtc-e6b35',
    authDomain: 'fir-rtc-e6b35.firebaseapp.com',
    databaseURL: 'https://fir-rtc-e6b35-default-rtdb.firebaseio.com',
    storageBucket: 'fir-rtc-e6b35.appspot.com',
    measurementId: 'G-8L6L2YJKSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGmXZso3d2Wntm1nBOwaUSCRDH7NkAMWU',
    appId: '1:500869155129:android:1cfbf90062773a06d8c0e8',
    messagingSenderId: '500869155129',
    projectId: 'fir-rtc-e6b35',
    databaseURL: 'https://fir-rtc-e6b35-default-rtdb.firebaseio.com',
    storageBucket: 'fir-rtc-e6b35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHUTNbVCl7HhlvH4MTW_nEs7gRg1L-9jk',
    appId: '1:500869155129:ios:ee0ba2130cdef71ad8c0e8',
    messagingSenderId: '500869155129',
    projectId: 'fir-rtc-e6b35',
    databaseURL: 'https://fir-rtc-e6b35-default-rtdb.firebaseio.com',
    storageBucket: 'fir-rtc-e6b35.appspot.com',
    iosBundleId: 'com.example.videochat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHUTNbVCl7HhlvH4MTW_nEs7gRg1L-9jk',
    appId: '1:500869155129:ios:ee0ba2130cdef71ad8c0e8',
    messagingSenderId: '500869155129',
    projectId: 'fir-rtc-e6b35',
    databaseURL: 'https://fir-rtc-e6b35-default-rtdb.firebaseio.com',
    storageBucket: 'fir-rtc-e6b35.appspot.com',
    iosBundleId: 'com.example.videochat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr4hgpdAJOADCpnXGv_U3atSSdwFsxdmc',
    appId: '1:500869155129:web:9aa4a8a43e0467a2d8c0e8',
    messagingSenderId: '500869155129',
    projectId: 'fir-rtc-e6b35',
    authDomain: 'fir-rtc-e6b35.firebaseapp.com',
    databaseURL: 'https://fir-rtc-e6b35-default-rtdb.firebaseio.com',
    storageBucket: 'fir-rtc-e6b35.appspot.com',
    measurementId: 'G-H1HF2LBXBC',
  );
}
